### ISSUE TITLE
"panic: can't find endpoint region" with Minio

### ISSUE THREAD

**Issue by AlexAkulov** [rlmcpherson/s3gof3r#138]
I try to use this library with Minio and I get `panic: can't find endpoint region`
My code:
```
	s3Client := s3gof3r.New(s.Config.Endpoint, s3gof3r.Keys{
		AccessKey: "my-access-key",
		SecretKey: "my-secret-key",
	})
	bucket := s3Client.Bucket("test")
	w, err := bucket.PutWriter(s3Path, nil, &s3gof3r.Config{
		Client: s3gof3r.ClientWithTimeout(5 * time.Second),
		Concurrency: 10,
		PartSize:    5 * 1024 * 1024,
		NTry:        3,
		Scheme:      "http",
		PathStyle:   "minio:9000",
	})
```
How can I set region for my custom endpoint?

**Comment by i0x71** [comment]
Any news on this ?
I am having the same issue
echo test | ./gof3r put -k obj -b dump --endpoint=xxxxx:9000
panic: can't find endpoint region

goroutine 1 [running]:
github.com/rlmcpherson/s3gof3r.(*S3).Region(0xc82004e400, 0x0, 0x0)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/s3gof3r.go:39 +0x1ce
github.com/rlmcpherson/s3gof3r.(*Bucket).Sign(0xc820010920, 0xc8200ce000)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/sign.go:56 +0x164
github.com/rlmcpherson/s3gof3r.(*putter).retryRequest(0xc820001080, 0x7fca00, 0x4, 0xc820013d70, 0x26, 0x0, 0x0, 0xc820013d10, 0x0, 0x0, ...)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/putter.go:382 +0x37e
github.com/rlmcpherson/s3gof3r.newPutter(0x7fe8d8, 0x5, 0x0, 0x0, 0x0, 0xc820010900, 0x12, 0xc82000ff20, 0x4, 0x0, ...)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/putter.go:88 +0x349
github.com/rlmcpherson/s3gof3r.(*Bucket).PutWriter(0xc82003d9e0, 0x7ffef5ff9d67, 0x3, 0xc820013d10, 0xc82003da90, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/s3gof3r.go:135 +0x126
main.(*putOpts).Execute(0x9d5a00, 0xc820018240, 0x0, 0x6, 0x7f4c660b2590, 0xc820013d40)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/gof3r/put.go:53 +0x65f
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc820014500, 0xc82000a1d0, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/jessevdk/go-flags/parser.go:301 +0xa16
github.com/jessevdk/go-flags.(*Parser).Parse(0xc820014500, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/jessevdk/go-flags/parser.go:175 +0x9b
main.main()
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/gof3r/main.go:61 +0x191

**Comment by Liuc46** [comment]
I hit the same issue , any new update for this error?
admin@localhost:~/MPU/gof3r_0.5.0_linux_amd64> ./gof3r get -b BucketE -k c49cy9e3x6oz --endpoint=192.168.200.7:443 --no-ssl
panic: can't find endpoint region

goroutine 1 [running]:
github.com/rlmcpherson/s3gof3r.(*S3).Region(0xc8200923c0, 0x0, 0x0)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/s3gof3r.go:39 +0x1ce
github.com/rlmcpherson/s3gof3r.(*Bucket).Sign(0xc820090820, 0xc820106000)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/sign.go:56 +0x164
github.com/rlmcpherson/s3gof3r.(*getter).retryRequest(0xc8201042c0, 0x7fc150, 0x3, 0xc82009bd70, 0x2d, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/getter.go:113 +0x1ae
github.com/rlmcpherson/s3gof3r.newGetter(0x7fe8c8, 0x4, 0x0, 0x0, 0x0, 0xc820090840, 0x19, 0xc820097e10, 0xd, 0x0, ...)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/getter.go:73 +0x589
github.com/rlmcpherson/s3gof3r.(*Bucket).GetReader(0xc820090820, 0x7fff222a8b0f, 0xc, 0xc820061a90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/s3gof3r.go:117 +0x238
main.(*getOpts).Execute(0x9d5880, 0xc82008fb20, 0x0, 0x7, 0x7f7454b0c568, 0xc82009bd10)
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/gof3r/get.go:54 +0x823
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc8200a84b0, 0xc8200a6010, 0x7, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/jessevdk/go-flags/parser.go:301 +0xa16
github.com/jessevdk/go-flags.(*Parser).Parse(0xc8200a84b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/rm/src/github.com/jessevdk/go-flags/parser.go:175 +0x9b
main.main()
        /Users/rm/src/github.com/rlmcpherson/s3gof3r/gof3r/main.go:61 +0x191
